# Configure development environment
spring.profiles.active: dev
server:
  port: 8080
  
# Remove spring icon
spring.mvc.favicon.enabled: false

# Spring configuration
spring:
  application:
    name: mbg-business
  session.store-type: none 
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis config
# Mapper文件路径
mybatis:
  mapper-locations: classpath*:com/ywd/mapper/**/*.xml